services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  sqlserver_data:
# For setting up a PostgreSQL database using Docker Compose
# services:
#   postgres:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root1234
#       POSTGRES_DB: reservation_tracker
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./initdb:/docker-entrypoint-initdb.d
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data:
